name: Checks

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
        
    steps:
    - uses: actions/checkout@v4
  
    - name: Install uv
      uses: astral-sh/setup-uv@v3
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: ".python-version"
          
    - name: Create environment
      run: uv sync --all-extras --dev
    
    - name: Run ruff
      run: uv run ruff check $(git ls-files '*.py')
        
    - name: Run pylint
      run: uv run pylint $(git ls-files '*.py')

    - name: Run pytest
      run: uv run pytest . -vvv -m 'not integration'
